
baseURL = "https://aidrivenengineering.com/"
languageCode = "en-us"
title = "AI Driven Engineering"
theme = "PaperMod"
enableGitInfo = true
paginate = 5

[params]
  author = "Helen"
  description = "My blog about data driven engineering."
  showReadingTime = true
  
[taxonomies]
  category = "categories"
  tag = "tags"
